- name: Get hostname and IP for all inventory hosts
  hosts: all
  gather_facts: true   # needed to get ansible_default_ipv4

  tasks:

    - name: Run hostname command
      command: hostname
      register: hostname_output

    - name: Print hostname and IP address
      debug:
        msg: "Host: {{ hostname_output.stdout }} | IP: {{ ansible_default_ipv4.address }}"
