---
- name: Remove password-related lines from bash history for all users
  hosts: all
  become: yes
  become_user: root
  gather_facts: no

  vars:
    password_keywords:
      - "password"
      - "passwd"
      - "pwd"
      - "pass="
      - "--password"
      - "-p"
      - "secret"
      - "token"
      - "key="

  tasks:
    - name: Get list of users with bash shell and existing home directories
      shell: |
        getent passwd | while IFS=: read -r user x uid gid gecos home shell; do
          if [[ "$shell" == *bash ]] && [[ -d "$home" ]]; then
            echo "$user:$home"
          fi
        done
      register: bash_users_result
      changed_when: false

    - name: Debug - Display found bash users
      debug:
        msg: "Found bash users: {{ bash_users_result.stdout_lines }}"

    - name: Clean bash history for each user
      shell: |
        user="{{ item.split(':')[0] }}"
        home="{{ item.split(':')[1] }}"
        history_file="$home/.bash_history"
        if [ -f "$history_file" ]; then
          temp_file=$(mktemp)
          original_lines=$(wc -l < "$history_file")
          grep -v -i -E "{{ keywords_pattern }}" "$history_file" > "$temp_file"
          cleaned_lines=$(wc -l < "$temp_file")
          removed_lines=$((original_lines - cleaned_lines))
          mv "$temp_file" "$history_file"
          chown "$user:$user" "$history_file"
          chmod 600 "$history_file"
          echo "Cleaned $history_file: removed $removed_lines lines"
        else
          echo "No .bash_history for user $user at $history_file"
        fi
      loop: "{{ bash_users_result.stdout_lines }}"
      vars:
        keywords_pattern: "{{ password_keywords | join('|') }}"
      when: bash_users_result.stdout_lines | length > 0

    - name: Confirm completion
      debug:
        msg: "Bash history cleaning completed for all users."
