---
- name: Remove password-related lines from bash history for all users
  hosts: all
  become: yes
  become_user: root
  gather_facts: no

  vars:
    password_keywords:
      - "password"
      - "passwd"
      - "pwd"
      - "pass="
      - "--password"
      - "-p "
      - "secret"
      - "token"
      - "key="

  tasks:
    - name: Get list of users with bash shell and existing home directories
      shell: |
        getent passwd | while IFS=: read -r user x uid gid gecos home shell; do
          if [[ "$shell" == *"bash"* ]] && [[ -d "$home" ]]; then
            echo "$user:$home"
          fi
        done
      register: bash_users_result
      changed_when: false

    - name: Display users to be processed
      debug:
        msg: "Found bash users: {{ bash_users_result.stdout_lines }}"
      when: bash_users_result.stdout_lines | length > 0

    - name: Clean bash history files by removing password-related lines
      shell: |
        home_dir="{{ item.split(':')[1] }}"
        user_name="{{ item.split(':')[0] }}"
        history_file="$home_dir/.bash_history"
        if [ -f "$history_file" ]; then
          temp_file=$(mktemp)
          original_lines=$(wc -l < "$history_file")
          grep -v -i -E "({{ password_keywords | join('|') }})" "$history_file" > "$temp_file"
          cleaned_lines=$(wc -l < "$temp_file")
          removed_lines=$((original_lines - cleaned_lines))
          mv "$temp_file" "$history_file"
          chown --reference="$home_dir" "$history_file"
          chmod 600 "$history_file"
          echo "Processed $history_file for user $user_name: removed $removed_lines lines"
        else
          echo "No .bash_history found for user $user_name at $history_file"
        fi
      loop: "{{ bash_users_result.stdout_lines }}"
      when: bash_users_result.stdout_lines | length > 0
      register: clean_result

    - name: Display cleaning results
      debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ clean_result.results }}"
      when: item.stdout_lines is defined and item.stdout_lines | length > 0

    - name: Confirm completion
      debug:
        msg: "Bash history cleaning completed for all users."
