    - name: Remove password‑containing lines from bash history files
      shell: |
        # build a case‑insensitive regex; '\b-p\b' matches -p as a standalone word
        regex='(?i).*(password|passwd|pwd|pass=|--password|\b-p\b|secret|token|key=).*'

        # extract home dir & user
        user="{{ item.split(':')[0] }}"
        home="{{ item.split(':')[1] }}"

        # loop over all history files in that home
        for hist in "$home"/.bash_history*; do
          [[ -f "$hist" && -r "$hist" && -w "$hist" ]] || continue

          # delete matching lines in place
          sed -i -E "/$regex/d" "$hist"

          # restore perms & ownership
          chown "$user":"$user" "$hist" 2>/dev/null || true
          chmod 600 "$hist"             2>/dev/null || true
        done
      loop: "{{ bash_users_result.stdout_lines }}"
      when: bash_users_result.stdout_lines | length > 0
      register: clean_result
