- name: Remove password‑containing lines from bash history for all users
  hosts: all
  become: yes
  gather_facts: no

  vars:
    password_keywords:
      - "password"
      - "passwd"
      - "pwd"
      - "pass="
      - "--password"
      - "\b-p\b"
      - "secret"
      - "token"
      - "key="

  tasks:                        # ← here’s your tasks: block
    - name: Remove password‑containing lines from bash history files
      shell: |
        regex='(?i).*(password|passwd|pwd|pass=|--password|\b-p\b|secret|token|key=).*'
        user="{{ item.split(':')[0] }}"
        home="{{ item.split(':')[1] }}"
        for hist in "$home"/.bash_history*; do
          [[ -f "$hist" && -r "$hist" && -w "$hist" ]] || continue
          sed -i -E "/$regex/d" "$hist"
          chown "$user":"$user" "$hist" 2>/dev/null || true
          chmod 600 "$hist"             2>/dev/null || true
        done
      loop: "{{ bash_users_result.stdout_lines }}"
      when: bash_users_result.stdout_lines | length > 0
      register: clean_result
